<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9776" started-at="2016-02-21T19:48:13Z" finished-at="2016-02-21T19:48:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9776" started-at="2016-02-21T19:48:13Z" finished-at="2016-02-21T19:48:23Z">
      <class name="com.vsii.tsc.TSCSelenium.khaidq.TestLoginSuccess">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.vsii.tsc.TSCSelenium.khaidq.TestLoginSuccess@23223dd8]" name="setUp" is-config="true" duration-ms="5272" started-at="2016-02-22T02:48:13Z" finished-at="2016-02-22T02:48:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testLoginSuccess()[pri:0, instance:com.vsii.tsc.TSCSelenium.khaidq.TestLoginSuccess@23223dd8]" name="testLoginSuccess" duration-ms="3971" started-at="2016-02-22T02:48:18Z" finished-at="2016-02-22T02:48:22Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.vsii.tsc.TSCSelenium.khaidq.TestLoginSuccess.testLoginSuccess(TestLoginSuccess.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginSuccess -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.vsii.tsc.TSCSelenium.khaidq.TestLoginSuccess@23223dd8]" name="tearDown" is-config="true" duration-ms="522" started-at="2016-02-22T02:48:22Z" finished-at="2016-02-22T02:48:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.vsii.tsc.TSCSelenium.khaidq.TestLoginSuccess -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
